import "./globals.css";
import Link from "next/link";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Planner",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} font-sans`}>
      <body className="bg-neutral-900 text-white min-h-screen">
        <nav className="shadow-lg">
          <div className="flex gap-3 p-3 bg-neutral-700">
            <Link href={"/calendar"}>Calendar</Link>
            <Link href={"/employees"}>Employees</Link>
          </div>
        </nav>
        <main className="p-3">{children}</main>
      </body>
    </html>
  );
}
